import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useRouter } from "expo-router";
import { PrimaryButton } from "@/components/primary-button";
import { SectionTitle } from "@/components/section-title";
import { dateInputValue, parseLocalDateInput } from "@/lib/format";
import { addCalendarEntry } from "@/lib/local-data";
import { CalendarEntry, makeId } from "@/shared/records";
import { ScreenContainer } from "@/components/screen-container";
const CATEGORIES: CalendarEntry["category"][] = ["Pessoal", "Saúde", "Trabalho", "Outro"];
export default function CalendarEntryScreen() { const router = useRouter(); const [title, setTitle] = useState(""); const [startsAt, setStartsAt] = useState(dateInputValue()); const [endsAt, setEndsAt] = useState(""); const [category, setCategory] = useState<CalendarEntry["category"]>("Pessoal"); const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false); const save = async () => { if (!title.trim()) { Alert.alert("Informe um título", "Dê um nome para o evento antes de salvar."); return; } setSaving(true); try { await addCalendarEntry({ id: makeId("calendar"), title: title.trim(), category, startsAt: parseLocalDateInput(startsAt), endsAt: endsAt.trim() ? parseLocalDateInput(endsAt) : undefined, notes: notes.trim() || undefined }); router.back(); } catch { Alert.alert("Não foi possível salvar", "Tente novamente em alguns instantes."); } finally { setSaving(false); } }; return <ScreenContainer className="px-5" edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.root}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><SectionTitle eyebrow="Agenda local" title="Novo evento" detail="Este evento pertence somente ao calendário interno do Registro Pessoal." /><Field label="Título" placeholder="Ex.: Consulta, passeio, reunião" value={title} onChangeText={setTitle} /><Field label="Início" placeholder="AAAA-MM-DDTHH:MM" value={startsAt} onChangeText={setStartsAt} autoCapitalize="none" /><Field label="Término (opcional)" placeholder="AAAA-MM-DDTHH:MM" value={endsAt} onChangeText={setEndsAt} autoCapitalize="none" /><Text style={styles.label}>Categoria</Text><View style={styles.categoryRow}>{CATEGORIES.map((item) => <TouchableOpacity key={item} onPress={() => setCategory(item)} style={[styles.category, category === item && styles.categoryActive]}><Text style={[styles.categoryLabel, category === item && styles.categoryLabelActive]}>{item}</Text></TouchableOpacity>)}</View><Field label="Observação (opcional)" placeholder="Informação adicional" value={notes} onChangeText={setNotes} multiline /><PrimaryButton label="Salvar evento" variant="calendar" onPress={save} loading={saving} style={styles.submit} /></ScrollView></KeyboardAvoidingView></ScreenContainer>; }
function Field({ label, multiline = false, ...inputProps }: { label: string; multiline?: boolean; value: string; onChangeText: (value: string) => void; placeholder: string; autoCapitalize?: "none" | "sentences" }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.textarea]} placeholderTextColor="#8DA0A7" multiline={multiline} textAlignVertical={multiline ? "top" : "center"} returnKeyType="done" {...inputProps} /></View>; }
const styles = StyleSheet.create({ root: { flex: 1 }, content: { paddingBottom: 28, paddingTop: 10 }, field: { marginBottom: 16 }, label: { color: "#344C56", fontSize: 13, fontWeight: "800", marginBottom: 7 }, input: { backgroundColor: "#FFFFFF", borderColor: "#D9E3E7", borderRadius: 14, borderWidth: 1, color: "#152A33", fontSize: 16, minHeight: 50, paddingHorizontal: 14 }, textarea: { minHeight: 106, paddingTop: 13 }, categoryRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 17 }, category: { backgroundColor: "#EDF2F4", borderRadius: 20, paddingHorizontal: 13, paddingVertical: 10 }, categoryActive: { backgroundColor: "#6966B3" }, categoryLabel: { color: "#526873", fontSize: 13, fontWeight: "700" }, categoryLabelActive: { color: "#FFFFFF" }, submit: { marginTop: 6 } });
