import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { PrimaryButton } from "@/components/primary-button";
import { SectionTitle } from "@/components/section-title";
import { dateInputValue, parseLocalDateInput } from "@/lib/format";
import { addHealthEntry } from "@/lib/local-data";
import { makeId } from "@/shared/records";
import { ScreenContainer } from "@/components/screen-container";
export default function HealthEntryScreen() { const router = useRouter(); const [metricName, setMetricName] = useState(""); const [value, setValue] = useState(""); const [unit, setUnit] = useState(""); const [category, setCategory] = useState("Geral"); const [recordedAt, setRecordedAt] = useState(dateInputValue()); const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false); const save = async () => { const numericValue = Number(value.replace(",", ".")); if (!metricName.trim() || !unit.trim() || !Number.isFinite(numericValue)) { Alert.alert("Verifique os campos", "Informe uma métrica, um valor numérico e a unidade."); return; } setSaving(true); try { await addHealthEntry({ id: makeId("health"), metricName: metricName.trim(), value: numericValue, unit: unit.trim(), category: category.trim() || "Geral", recordedAt: parseLocalDateInput(recordedAt), notes: notes.trim() || undefined }); router.back(); } catch { Alert.alert("Não foi possível salvar", "Tente novamente em alguns instantes."); } finally { setSaving(false); } }; return <ScreenContainer className="px-5" edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.root}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><SectionTitle eyebrow="Dado inserido manualmente" title="Novo registro de saúde" detail="Este app organiza seus dados; não interpreta ou diagnostica informações de saúde." /><Field label="Métrica" placeholder="Ex.: Peso, pressão, sono" value={metricName} onChangeText={setMetricName} /><View style={styles.row}><View style={styles.flex}><Field label="Valor" placeholder="Ex.: 72,5" value={value} onChangeText={setValue} keyboardType="decimal-pad" /></View><View style={styles.unit}><Field label="Unidade" placeholder="Ex.: kg" value={unit} onChangeText={setUnit} /></View></View><Field label="Categoria" placeholder="Ex.: Bem-estar" value={category} onChangeText={setCategory} /><Field label="Data e hora" placeholder="AAAA-MM-DDTHH:MM" value={recordedAt} onChangeText={setRecordedAt} autoCapitalize="none" /><Field label="Observação (opcional)" placeholder="Contexto que você queira guardar" value={notes} onChangeText={setNotes} multiline /><PrimaryButton label="Salvar registro" variant="health" onPress={save} loading={saving} style={styles.submit} /></ScrollView></KeyboardAvoidingView></ScreenContainer>; }
function Field({ label, multiline = false, ...inputProps }: { label: string; multiline?: boolean; value: string; onChangeText: (value: string) => void; placeholder: string; keyboardType?: "default" | "decimal-pad"; autoCapitalize?: "none" | "sentences" }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.textarea]} placeholderTextColor="#8DA0A7" multiline={multiline} textAlignVertical={multiline ? "top" : "center"} returnKeyType="done" {...inputProps} /></View>; }
const styles = StyleSheet.create({ root: { flex: 1 }, content: { paddingBottom: 28, paddingTop: 10 }, row: { flexDirection: "row", gap: 12 }, flex: { flex: 1 }, unit: { width: 100 }, field: { marginBottom: 16 }, label: { color: "#344C56", fontSize: 13, fontWeight: "800", marginBottom: 7 }, input: { backgroundColor: "#FFFFFF", borderColor: "#D9E3E7", borderRadius: 14, borderWidth: 1, color: "#152A33", fontSize: 16, minHeight: 50, paddingHorizontal: 14 }, textarea: { minHeight: 106, paddingTop: 13 }, submit: { marginTop: 6 } });
