import { useCallback, useMemo, useState } from "react";
import { Alert, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";
import { EmptyState } from "@/components/empty-state";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { PrimaryButton } from "@/components/primary-button";
import { SectionTitle } from "@/components/section-title";
import { formatDateTime, formatShortDate } from "@/lib/format";
import { deleteEntry, loadAppData } from "@/lib/local-data";
import { AppData, CalendarEntry, EMPTY_APP_DATA } from "@/shared/records";
import { ScreenContainer } from "@/components/screen-container";
export default function CalendarScreen() { const router = useRouter(); const [data, setData] = useState<AppData>(EMPTY_APP_DATA); useFocusEffect(useCallback(() => { loadAppData().then(setData); }, [])); const upcoming = useMemo(() => data.calendarEntries.filter((entry) => new Date(entry.startsAt) >= new Date()), [data.calendarEntries]); const past = useMemo(() => data.calendarEntries.filter((entry) => new Date(entry.startsAt) < new Date()).reverse(), [data.calendarEntries]); const entries = [...upcoming, ...past]; const confirmDelete = (id: string) => Alert.alert("Excluir evento?", "O evento será removido do calendário interno.", [{ text: "Cancelar", style: "cancel" }, { text: "Excluir", style: "destructive", onPress: () => deleteEntry("calendar", id).then(setData) }]); return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.root}><SectionTitle eyebrow="Agenda interna" title="Calendário" detail="Organize compromissos sem acessar o calendário do sistema." /><PrimaryButton label="Novo evento" variant="calendar" icon={<IconSymbol name="plus" size={20} color="#FFFFFF" />} onPress={() => router.push("/calendar-entry" as never)} /><Text style={styles.caption}>{upcoming.length ? `${upcoming.length} evento${upcoming.length === 1 ? "" : "s"} futuro${upcoming.length === 1 ? "" : "s"}` : "Sua próxima agenda aparecerá aqui"}</Text><FlatList data={entries} keyExtractor={(entry) => entry.id} contentContainerStyle={entries.length ? styles.list : styles.emptyList} showsVerticalScrollIndicator={false} ListEmptyComponent={<EmptyState icon={<IconSymbol name="calendar" size={25} color="#6966B3" />} title="Nenhum evento adicionado" description="Crie seus compromissos pessoais para acompanhá-los neste app." />} renderItem={({ item }) => <CalendarItem item={item} onDelete={() => confirmDelete(item.id)} />} /></View></ScreenContainer>; }
function CalendarItem({ item, onDelete }: { item: CalendarEntry; onDelete: () => void }) { const categoryColor = item.category === "Saúde" ? "#3F8D72" : item.category === "Trabalho" ? "#176B87" : item.category === "Pessoal" ? "#6966B3" : "#789098"; return <View style={styles.item}><View style={[styles.dateBox, { backgroundColor: `${categoryColor}16` }]}><Text style={[styles.dateMain, { color: categoryColor }]}>{formatShortDate(item.startsAt).slice(0, 2)}</Text><Text style={[styles.dateMonth, { color: categoryColor }]}>{formatShortDate(item.startsAt).slice(3)}</Text></View><View style={styles.itemBody}><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.itemDetail}>{formatDateTime(item.startsAt)}</Text><Text style={[styles.category, { color: categoryColor }]}>{item.category}</Text></View><TouchableOpacity style={styles.delete} onPress={onDelete}><IconSymbol name="trash" size={18} color="#9A4A4A" /></TouchableOpacity></View>; }
const styles = StyleSheet.create({ root: { flex: 1, paddingTop: 10 }, caption: { color: "#789098", fontSize: 12, fontWeight: "700", marginTop: 18, textTransform: "uppercase" }, list: { gap: 10, paddingBottom: 24, paddingTop: 10 }, emptyList: { flexGrow: 1, justifyContent: "center", paddingBottom: 60 }, item: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E2E9EC", borderRadius: 18, borderWidth: 1, flexDirection: "row", minHeight: 82, padding: 12 }, dateBox: { alignItems: "center", borderRadius: 12, height: 48, justifyContent: "center", marginRight: 12, width: 48 }, dateMain: { fontSize: 16, fontWeight: "800", lineHeight: 19 }, dateMonth: { fontSize: 11, fontWeight: "700", lineHeight: 13 }, itemBody: { flex: 1 }, itemTitle: { color: "#152A33", fontSize: 15, fontWeight: "800" }, itemDetail: { color: "#60747C", fontSize: 12, marginTop: 3 }, category: { fontSize: 12, fontWeight: "700", marginTop: 4 }, delete: { alignItems: "center", height: 38, justifyContent: "center", marginLeft: 8, width: 38 } });
