import { useCallback, useState } from "react";
import { Alert, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";

import { EmptyState } from "@/components/empty-state";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { PrimaryButton } from "@/components/primary-button";
import { SectionTitle } from "@/components/section-title";
import { formatDateTime } from "@/lib/format";
import { deleteEntry, loadAppData } from "@/lib/local-data";
import { bodySiteDetailLabel, chronicConditionLabel, emotionLabel, foodLabel, painTypeLabel, AppData, EMPTY_APP_DATA, PainEntry } from "@/shared/records";
import { ScreenContainer } from "@/components/screen-container";

export default function RecordsScreen() {
  const router = useRouter();
  const [data, setData] = useState<AppData>(EMPTY_APP_DATA);
  useFocusEffect(useCallback(() => { loadAppData().then(setData); }, []));
  const confirmDelete = (id: string) => Alert.alert("Excluir ocorrência?", "O registro será removido somente deste aparelho.", [{ text: "Cancelar", style: "cancel" }, { text: "Excluir", style: "destructive", onPress: () => deleteEntry("pain", id).then(setData) }]);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.root}><SectionTitle eyebrow="Histórico local" title="Ocorrências" detail="Cada registro reúne dor, contexto e clima do momento." /><PrimaryButton label="Registrar nova dor" variant="health" icon={<IconSymbol name="plus" size={20} color="#FFFFFF" />} onPress={() => router.push("/pain-entry" as never)} /><FlatList<PainEntry> data={data.painEntries} keyExtractor={(entry) => entry.id} contentContainerStyle={data.painEntries.length ? styles.list : styles.emptyList} showsVerticalScrollIndicator={false} ListEmptyComponent={<EmptyState icon={<IconSymbol name="heart.fill" size={25} color="#3F8D72" />} title="Nenhuma ocorrência registrada" description="Toque em uma região do corpo para iniciar seu primeiro registro visual." />} renderItem={({ item }) => <PainItem item={item} onDelete={() => confirmDelete(item.id)} onPress={() => router.push(`/pain-detail?id=${encodeURIComponent(item.id)}` as never)} />} /></View></ScreenContainer>;
}

function PainItem({ item, onDelete, onPress }: { item: PainEntry; onDelete: () => void; onPress: () => void }) { const typeNames = item.painTypes.slice(0, 2).map(painTypeLabel).join(" · "); const foodNames = item.foods.filter((food) => food !== "none").slice(0, 2).map(foodLabel).join(" · "); const conditionNames = (item.conditions ?? []).slice(0, 2).map(chronicConditionLabel).join(" · "); return <TouchableOpacity accessibilityRole="button" accessibilityLabel="Abrir detalhes da ocorrência" onPress={onPress} activeOpacity={0.86} style={styles.item}><View style={styles.iconBox}><IconSymbol name="heart.fill" size={21} color="#E98B5A" /></View><View style={styles.itemBody}><Text style={styles.itemTitle}>{bodySiteDetailLabel(item.primaryDetail ?? item.primarySite)} · {item.intensity}/10</Text><Text style={styles.itemDetail}>{formatDateTime(item.occurredAt)} · {emotionLabel(item.emotion)}</Text><Text numberOfLines={1} style={styles.itemMeta}>{typeNames || "Sensação não informada"}</Text>{item.radiationDetails?.length ? <Text numberOfLines={1} style={styles.itemMeta}>Irradia: {item.radiationDetails.slice(0, 2).map(bodySiteDetailLabel).join(" → ")}</Text> : null}{conditionNames ? <Text numberOfLines={1} style={styles.itemMeta}>Contexto: {conditionNames}</Text> : null}{item.weather ? <Text style={styles.itemMeta}>Clima: {Math.round(item.weather.temperature)}°C{item.weather.locality ? ` · ${item.weather.locality}` : ""}</Text> : null}{foodNames ? <Text numberOfLines={1} style={styles.itemMeta}>Alimentação: {foodNames}</Text> : null}</View><TouchableOpacity accessibilityRole="button" accessibilityLabel="Excluir ocorrência" style={styles.delete} onPress={onDelete}><IconSymbol name="trash" size={18} color="#9A4A4A" /></TouchableOpacity></TouchableOpacity>; }

const styles = StyleSheet.create({ root: { flex: 1, paddingTop: 10 }, list: { gap: 10, paddingBottom: 25, paddingTop: 16 }, emptyList: { flexGrow: 1, justifyContent: "center", paddingBottom: 64 }, item: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E2E9EC", borderRadius: 18, borderWidth: 1, flexDirection: "row", minHeight: 100, padding: 12 }, iconBox: { alignItems: "center", backgroundColor: "#FFF0E8", borderRadius: 12, height: 42, justifyContent: "center", marginRight: 12, width: 42 }, itemBody: { flex: 1 }, itemTitle: { color: "#152A33", fontSize: 15, fontWeight: "800" }, itemDetail: { color: "#60747C", fontSize: 12, marginTop: 3 }, itemMeta: { color: "#789098", fontSize: 12, marginTop: 4 }, delete: { alignItems: "center", height: 42, justifyContent: "center", marginLeft: 8, width: 42 } });
