import { useCallback, useMemo, useState } from "react";
import { Alert, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Swipeable } from "react-native-gesture-handler";
import { useFocusEffect, useRouter } from "expo-router";
import { EmptyState } from "@/components/empty-state";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { PrimaryButton } from "@/components/primary-button";
import { SectionTitle } from "@/components/section-title";
import { formatDateTime } from "@/lib/format";
import { deleteEntry, loadAppData } from "@/lib/local-data";
import { bodySiteDetailLabel, chronicConditionLabel, emotionLabel, foodLabel, PainEntry, painTypeLabel, AppData, EMPTY_APP_DATA } from "@/shared/records";
import { ScreenContainer } from "@/components/screen-container";

type Period = 7 | 30 | 90;
export default function RecordsScreen() {
  const router = useRouter(); const [data, setData] = useState<AppData>(EMPTY_APP_DATA); const [period, setPeriod] = useState<Period>(30); const [intensity, setIntensity] = useState<"all" | "low" | "medium" | "high">("all"); const [site, setSite] = useState("all");
  useFocusEffect(useCallback(() => { loadAppData().then(setData); }, []));
  const sites = useMemo(() => Array.from(new Set(data.painEntries.map((entry) => bodySiteDetailLabel(entry.primaryDetail ?? entry.primarySite)))), [data.painEntries]);
  const visible = useMemo(() => { const since = Date.now() - period * 86_400_000; return data.painEntries.filter((entry) => new Date(entry.occurredAt).getTime() >= since && (intensity === "all" || (intensity === "low" && entry.intensity <= 3) || (intensity === "medium" && entry.intensity >= 4 && entry.intensity <= 6) || (intensity === "high" && entry.intensity >= 7)) && (site === "all" || bodySiteDetailLabel(entry.primaryDetail ?? entry.primarySite) === site)); }, [data.painEntries, period, intensity, site]);
  const confirmDelete = (id: string) => Alert.alert("Mover para apagados?", "A ocorrência ficará na lixeira e não será excluída permanentemente.", [{ text: "Cancelar", style: "cancel" }, { text: "Mover", style: "destructive", onPress: () => deleteEntry("pain", id).then(setData) }]);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.root}><SectionTitle eyebrow="Histórico local" title="Ocorrências" detail="Deslize um cartão para editar ou mover para apagados." /><View style={styles.filterRow}><Filter label="7d" active={period === 7} onPress={() => setPeriod(7)} /><Filter label="30d" active={period === 30} onPress={() => setPeriod(30)} /><Filter label="90d" active={period === 90} onPress={() => setPeriod(90)} /></View><View style={styles.filterRow}><Filter label="Todas" active={intensity === "all"} onPress={() => setIntensity("all")} /><Filter label="1–3" active={intensity === "low"} onPress={() => setIntensity("low")} /><Filter label="4–6" active={intensity === "medium"} onPress={() => setIntensity("medium")} /><Filter label="7–10" active={intensity === "high"} onPress={() => setIntensity("high")} /></View>{sites.length ? <FlatList horizontal data={["all", ...sites]} keyExtractor={(item) => item} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.siteFilters} renderItem={({ item }) => <Filter label={item === "all" ? "Todos os locais" : item} active={site === item} onPress={() => setSite(item)} />} /> : null}<PrimaryButton label="Registrar nova dor" variant="health" icon={<IconSymbol name="plus" size={20} color="#FFFFFF" />} onPress={() => router.push("/pain-entry" as never)} /><FlatList<PainEntry> data={visible} keyExtractor={(entry) => entry.id} contentContainerStyle={visible.length ? styles.list : styles.emptyList} showsVerticalScrollIndicator={false} ListEmptyComponent={<EmptyState icon={<IconSymbol name="heart.fill" size={25} color="#3F8D72" />} title="Nenhuma ocorrência neste filtro" description="Ajuste os filtros ou registre uma nova ocorrência de dor." />} renderItem={({ item }) => <PainItem item={item} onDelete={() => confirmDelete(item.id)} onPress={() => router.push(`/pain-detail?id=${encodeURIComponent(item.id)}` as never)} />} /></View></ScreenContainer>;
}
function Filter({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <TouchableOpacity onPress={onPress} activeOpacity={0.8} style={[styles.filter, active && styles.filterActive]}><Text numberOfLines={1} style={[styles.filterText, active && styles.filterTextActive]}>{label}</Text></TouchableOpacity>; }
function PainItem({ item, onDelete, onPress }: { item: PainEntry; onDelete: () => void; onPress: () => void }) { const typeNames = item.painTypes.slice(0, 2).map(painTypeLabel).join(" · "); const foodNames = item.foods.filter((food) => food !== "none").slice(0, 2).map(foodLabel).join(" · "); const conditionNames = (item.conditions ?? []).slice(0, 2).map(chronicConditionLabel).join(" · "); return <Swipeable renderRightActions={() => <View style={styles.swipeActions}><TouchableOpacity accessibilityLabel="Editar ocorrência" onPress={onPress} style={styles.editAction}><Text style={styles.actionText}>Editar</Text></TouchableOpacity><TouchableOpacity accessibilityLabel="Mover ocorrência para apagados" onPress={onDelete} style={styles.deleteAction}><Text style={styles.actionText}>Apagar</Text></TouchableOpacity></View>}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Abrir detalhes da ocorrência" onPress={onPress} activeOpacity={0.86} style={styles.item}><View style={styles.iconBox}><IconSymbol name="heart.fill" size={21} color="#E98B5A" /></View><View style={styles.itemBody}><Text style={styles.itemTitle}>{bodySiteDetailLabel(item.primaryDetail ?? item.primarySite)} · {item.intensity}/10</Text><Text style={styles.itemDetail}>{formatDateTime(item.occurredAt)} · {emotionLabel(item.emotion)}</Text><Text numberOfLines={1} style={styles.itemMeta}>{typeNames || "Sensação não informada"}</Text>{item.localSymptoms?.length ? <Text numberOfLines={1} style={styles.itemMeta}>Sintomas: {item.localSymptoms.slice(0, 2).join(" · ")}</Text> : null}{item.radiationDetails?.length ? <Text numberOfLines={1} style={styles.itemMeta}>Irradia: {item.radiationDetails.slice(0, 2).map(bodySiteDetailLabel).join(" → ")}</Text> : null}{conditionNames ? <Text numberOfLines={1} style={styles.itemMeta}>Contexto: {conditionNames}</Text> : null}{item.weather ? <Text style={styles.itemMeta}>Clima: {Math.round(item.weather.temperature)}°C{item.weather.locality ? ` · ${item.weather.locality}` : ""}</Text> : null}{foodNames ? <Text numberOfLines={1} style={styles.itemMeta}>Alimentação: {foodNames}</Text> : null}</View><TouchableOpacity accessibilityRole="button" accessibilityLabel="Excluir ocorrência" style={styles.delete} onPress={onDelete}><IconSymbol name="trash" size={18} color="#9A4A4A" /></TouchableOpacity></TouchableOpacity></Swipeable>; }
const styles = StyleSheet.create({ root: { flex: 1, paddingTop: 10 }, filterRow: { flexDirection: "row", gap: 7, marginBottom: 8 }, filter: { backgroundColor: "#EDF2F4", borderRadius: 14, minHeight: 34, justifyContent: "center", paddingHorizontal: 13 }, filterActive: { backgroundColor: "#176B87" }, filterText: { color: "#526873", fontSize: 12, fontWeight: "700" }, filterTextActive: { color: "#FFFFFF" }, siteFilters: { gap: 7, paddingBottom: 13 }, list: { gap: 10, paddingBottom: 25, paddingTop: 16 }, emptyList: { flexGrow: 1, justifyContent: "center", paddingBottom: 64 }, item: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E2E9EC", borderRadius: 18, borderWidth: 1, flexDirection: "row", minHeight: 100, padding: 12 }, iconBox: { alignItems: "center", backgroundColor: "#FFF0E8", borderRadius: 12, height: 42, justifyContent: "center", marginRight: 12, width: 42 }, itemBody: { flex: 1 }, itemTitle: { color: "#152A33", fontSize: 15, fontWeight: "800" }, itemDetail: { color: "#60747C", fontSize: 12, marginTop: 3 }, itemMeta: { color: "#789098", fontSize: 12, marginTop: 4 }, delete: { alignItems: "center", height: 42, justifyContent: "center", marginLeft: 8, width: 42 }, swipeActions: { alignItems: "stretch", flexDirection: "row", marginBottom: 0 }, editAction: { backgroundColor: "#6966B3", justifyContent: "center", paddingHorizontal: 16 }, deleteAction: { backgroundColor: "#9A4A4A", justifyContent: "center", paddingHorizontal: 16 }, actionText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" } });
